#!/bin/bash

#
# MyJarbis Global Installation Script
#
# This script installs MyJarbis globally on your system:
# 1. Copies files to ~/.myjarbis-global/
# 2. Installs MCP server dependencies
# 3. Builds MCP server
# 4. Configures Claude Code (creates/updates ~/.config/claude/mcp.json)
# 5. Adds CLI to PATH
#
# Usage: ./install.sh
#

set -e  # Exit on error

# Colors for output - Iron Man theme (red and gold)
RED='\033[1;31m'      # Bright red (Iron Man red)
GOLD='\033[1;33m'     # Bright yellow/gold (Iron Man gold)
GREEN='\033[0;32m'    # Keep green for success
YELLOW='\033[1;33m'   # Warning yellow
NC='\033[0m'          # No Color

# Installation paths
INSTALL_DIR="$HOME/.myjarbis-global"
CLAUDE_CONFIG_DIR="$HOME/.config/claude"
CLAUDE_MCP_CONFIG="$CLAUDE_CONFIG_DIR/mcp.json"

echo ""
echo -e "${RED}╔════════════════════════════════════════════════╗${NC}"
echo -e "${RED}║${GOLD}              🤖 JARBIS INSTALLER              ${RED}║${NC}"
echo -e "${RED}║${NC}      Persistent Memory for Claude Code       ${RED}║${NC}"
echo -e "${RED}╚════════════════════════════════════════════════╝${NC}"
echo -e "${GOLD}   Developed by Braian Axel Troncoso 🇦🇷${NC}"
echo -e "${GOLD}   github.com/braiantroncoso${NC}"
echo ""

# Check if running from correct directory
if [ ! -f "package.json" ] || [ ! -d "global" ]; then
    echo -e "${RED}Error: Please run this script from the MyJarbis root directory${NC}"
    echo "Usage: ./install.sh"
    exit 1
fi

# Check for Node.js
echo -e "${GOLD}[1/7]${NC} Checking prerequisites..."
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    echo "Please install Node.js 18+ from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}Error: Node.js version 18 or higher required${NC}"
    echo "Current version: $(node --version)"
    exit 1
fi

echo -e "${GREEN}✓${NC} Node.js $(node --version) found"

# Check for npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} npm $(npm --version) found"

# Create installation directory
echo ""
echo -e "${GOLD}[2/7]${NC} Creating installation directory..."
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Warning: $INSTALL_DIR already exists${NC}"
    read -p "Remove existing installation and continue? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$INSTALL_DIR"
        echo -e "${GREEN}✓${NC} Removed existing installation"
    else
        echo "Installation cancelled"
        exit 0
    fi
fi

mkdir -p "$INSTALL_DIR"
echo -e "${GREEN}✓${NC} Created $INSTALL_DIR"

# Copy files
echo ""
echo -e "${GOLD}[3/7]${NC} Copying MyJarbis files..."
cp -r global/* "$INSTALL_DIR/"
cp -r bin "$INSTALL_DIR/"
echo -e "${GREEN}✓${NC} Files copied to $INSTALL_DIR"

# Initialize projects registry
echo ""
echo -e "${GOLD}[4/7]${NC} Initializing projects registry..."
REGISTRY_FILE="$INSTALL_DIR/projects-registry.json"
if [ ! -f "$REGISTRY_FILE" ]; then
    cat > "$REGISTRY_FILE" << 'EOF'
{
  "_comment": "This file is auto-generated by MyJarbis. Do not edit manually.",
  "_version": "1.0",
  "_lastUpdated": "$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")",
  "projects": {}
}
EOF
    echo -e "${GREEN}✓${NC} Created projects registry"
else
    echo -e "${YELLOW}!${NC} Projects registry already exists (keeping existing)"
fi

# Install MCP server dependencies
echo ""
echo -e "${GOLD}[5/7]${NC} Installing MCP server dependencies..."
cd "$INSTALL_DIR/mcp-server"
npm install --silent
echo -e "${GREEN}✓${NC} Dependencies installed"

# Build MCP server
echo ""
echo -e "${GOLD}[6/7]${NC} Building MCP server..."
npm run build --silent
echo -e "${GREEN}✓${NC} MCP server built successfully"

# Configure Claude Code
echo ""
echo -e "${GOLD}[7/7]${NC} Configuring Claude Code..."

# MCP server path
MCP_SERVER_PATH="$INSTALL_DIR/mcp-server/build/index.js"

# Check if claude CLI is available
if ! command -v claude &> /dev/null; then
    echo -e "${YELLOW}!${NC} Claude Code CLI not found"
    echo "Please install Claude Code first: https://claude.ai/claude-code"
    echo ""
    echo "After installing, run this command to configure MCP:"
    echo "  claude mcp add myjarbis node $MCP_SERVER_PATH"
    echo ""
else
    # Check if myjarbis MCP server is already configured
    if claude mcp list 2>/dev/null | grep -q "myjarbis"; then
        echo -e "${YELLOW}!${NC} MyJarbis MCP server already configured"
    else
        echo -e "${GOLD}Configuring MCP server...${NC}"
        claude mcp add myjarbis node "$MCP_SERVER_PATH" >/dev/null 2>&1

        # Verify it was added
        if claude mcp list 2>/dev/null | grep -q "myjarbis"; then
            echo -e "${GREEN}✓${NC} MyJarbis MCP server configured successfully"
        else
            echo -e "${RED}✗${NC} Failed to configure MCP server"
            echo "Please run manually: claude mcp add myjarbis node $MCP_SERVER_PATH"
        fi
    fi
fi

# Add to PATH (optional)
echo ""
echo -e "${GOLD}Setting up CLI...${NC}"

SHELL_RC=""
if [ -n "$BASH_VERSION" ]; then
    SHELL_RC="$HOME/.bashrc"
elif [ -n "$ZSH_VERSION" ]; then
    SHELL_RC="$HOME/.zshrc"
fi

if [ -n "$SHELL_RC" ]; then
    if ! grep -q "myjarbis-global/bin" "$SHELL_RC"; then
        echo "" >> "$SHELL_RC"
        echo "# MyJarbis CLI" >> "$SHELL_RC"
        echo "export PATH=\"\$HOME/.myjarbis-global/bin:\$PATH\"" >> "$SHELL_RC"
        echo -e "${GREEN}✓${NC} Added MyJarbis to PATH in $SHELL_RC"
        echo -e "${YELLOW}!${NC} Run 'source $SHELL_RC' or restart your terminal"
    else
        echo -e "${YELLOW}!${NC} MyJarbis already in PATH"
    fi
fi

# Make CLI scripts executable
chmod +x "$INSTALL_DIR/bin/myjarbis"
chmod +x "$INSTALL_DIR/bin/myjarbis-init"
chmod +x "$INSTALL_DIR/bin/myjarbis-update"

# Success message
echo ""
echo -e "${RED}╔════════════════════════════════════════════════╗${NC}"
echo -e "${RED}║${GREEN}     ✓ INSTALLATION COMPLETED SUCCESSFULLY    ${RED}║${NC}"
echo -e "${RED}╚════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GOLD}Next steps:${NC}"
echo ""
echo -e "${GOLD}1.${NC} Reload your shell:"
if [ -n "$SHELL_RC" ]; then
    echo -e "   ${GOLD}source $SHELL_RC${NC}"
fi
echo ""
echo -e "${GOLD}2.${NC} Navigate to a project:"
echo -e "   ${GOLD}cd ~/projects/my-project${NC}"
echo ""
echo -e "${GOLD}3.${NC} Initialize Jarbis:"
echo -e "   ${GOLD}myjarbis init${NC}"
echo ""
echo -e "${GOLD}4.${NC} Start Claude Code:"
echo -e "   ${GOLD}claude${NC}"
echo ""
echo -e "${GOLD}5.${NC} Initialize context:"
echo -e "   ${GOLD}/jarbis${NC}"
echo ""
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GOLD}Documentation:${NC} github.com/braiantroncoso/myjarbis"
echo -e "${GOLD}Created by:${NC} Braian Axel Troncoso 🇦🇷"
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
