#!/bin/bash

#
# MyJarvis Global Installation Script
#
# This script installs MyJarvis globally on your system:
# 1. Copies files to ~/.myjarvis-global/
# 2. Installs MCP server dependencies
# 3. Builds MCP server
# 4. Configures Claude Code (creates/updates ~/.config/claude/mcp.json)
# 5. Adds CLI to PATH
#
# Usage: ./install.sh
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Installation paths
INSTALL_DIR="$HOME/.myjarvis-global"
CLAUDE_CONFIG_DIR="$HOME/.config/claude"
CLAUDE_MCP_CONFIG="$CLAUDE_CONFIG_DIR/mcp.json"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  MyJarvis Global Installation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if running from correct directory
if [ ! -f "package.json" ] || [ ! -d "global" ]; then
    echo -e "${RED}Error: Please run this script from the MyJarvis root directory${NC}"
    echo "Usage: ./install.sh"
    exit 1
fi

# Check for Node.js
echo -e "${BLUE}[1/7]${NC} Checking prerequisites..."
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    echo "Please install Node.js 18+ from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}Error: Node.js version 18 or higher required${NC}"
    echo "Current version: $(node --version)"
    exit 1
fi

echo -e "${GREEN}✓${NC} Node.js $(node --version) found"

# Check for npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} npm $(npm --version) found"

# Create installation directory
echo ""
echo -e "${BLUE}[2/7]${NC} Creating installation directory..."
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Warning: $INSTALL_DIR already exists${NC}"
    read -p "Remove existing installation and continue? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$INSTALL_DIR"
        echo -e "${GREEN}✓${NC} Removed existing installation"
    else
        echo "Installation cancelled"
        exit 0
    fi
fi

mkdir -p "$INSTALL_DIR"
echo -e "${GREEN}✓${NC} Created $INSTALL_DIR"

# Copy files
echo ""
echo -e "${BLUE}[3/7]${NC} Copying MyJarvis files..."
cp -r global/* "$INSTALL_DIR/"
cp -r bin "$INSTALL_DIR/"
echo -e "${GREEN}✓${NC} Files copied to $INSTALL_DIR"

# Initialize projects registry
echo ""
echo -e "${BLUE}[4/7]${NC} Initializing projects registry..."
REGISTRY_FILE="$INSTALL_DIR/projects-registry.json"
if [ ! -f "$REGISTRY_FILE" ]; then
    cat > "$REGISTRY_FILE" << 'EOF'
{
  "_comment": "This file is auto-generated by MyJarvis. Do not edit manually.",
  "_version": "1.0",
  "_lastUpdated": "$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")",
  "projects": {}
}
EOF
    echo -e "${GREEN}✓${NC} Created projects registry"
else
    echo -e "${YELLOW}!${NC} Projects registry already exists (keeping existing)"
fi

# Install MCP server dependencies
echo ""
echo -e "${BLUE}[5/7]${NC} Installing MCP server dependencies..."
cd "$INSTALL_DIR/mcp-server"
npm install --silent
echo -e "${GREEN}✓${NC} Dependencies installed"

# Build MCP server
echo ""
echo -e "${BLUE}[6/7]${NC} Building MCP server..."
npm run build --silent
echo -e "${GREEN}✓${NC} MCP server built successfully"

# Configure Claude Code
echo ""
echo -e "${BLUE}[7/7]${NC} Configuring Claude Code..."

# Create Claude config directory if it doesn't exist
mkdir -p "$CLAUDE_CONFIG_DIR"

# Create or update mcp.json
MCP_SERVER_PATH="$INSTALL_DIR/mcp-server/build/index.js"

if [ -f "$CLAUDE_MCP_CONFIG" ]; then
    echo -e "${YELLOW}!${NC} Claude MCP config already exists"
    echo "You need to manually add MyJarvis to your $CLAUDE_MCP_CONFIG"
    echo ""
    echo "Add this to the 'mcpServers' section:"
    echo ""
    echo "  \"myjarvis\": {"
    echo "    \"command\": \"node\","
    echo "    \"args\": [\"$MCP_SERVER_PATH\"]"
    echo "  }"
    echo ""
else
    cat > "$CLAUDE_MCP_CONFIG" << EOF
{
  "mcpServers": {
    "myjarvis": {
      "command": "node",
      "args": ["$MCP_SERVER_PATH"]
    }
  }
}
EOF
    echo -e "${GREEN}✓${NC} Created $CLAUDE_MCP_CONFIG"
fi

# Add to PATH (optional)
echo ""
echo -e "${BLUE}Setting up CLI...${NC}"

SHELL_RC=""
if [ -n "$BASH_VERSION" ]; then
    SHELL_RC="$HOME/.bashrc"
elif [ -n "$ZSH_VERSION" ]; then
    SHELL_RC="$HOME/.zshrc"
fi

if [ -n "$SHELL_RC" ]; then
    if ! grep -q "myjarvis-global/bin" "$SHELL_RC"; then
        echo "" >> "$SHELL_RC"
        echo "# MyJarvis CLI" >> "$SHELL_RC"
        echo "export PATH=\"\$HOME/.myjarvis-global/bin:\$PATH\"" >> "$SHELL_RC"
        echo -e "${GREEN}✓${NC} Added MyJarvis to PATH in $SHELL_RC"
        echo -e "${YELLOW}!${NC} Run 'source $SHELL_RC' or restart your terminal"
    else
        echo -e "${YELLOW}!${NC} MyJarvis already in PATH"
    fi
fi

# Make CLI scripts executable
chmod +x "$INSTALL_DIR/bin/myjarvis"
chmod +x "$INSTALL_DIR/bin/myjarvis-init"
chmod +x "$INSTALL_DIR/bin/myjarvis-update"

# Success message
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Installation completed successfully!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo ""
echo "1. Reload your shell:"
if [ -n "$SHELL_RC" ]; then
    echo "   source $SHELL_RC"
fi
echo ""
echo "2. Navigate to a project:"
echo "   cd ~/projects/my-project"
echo ""
echo "3. Initialize MyJarvis:"
echo "   myjarvis init"
echo ""
echo "4. Start Claude Code:"
echo "   claude"
echo ""
echo "For help:"
echo "   myjarvis help"
echo ""
echo "Documentation: https://github.com/braiantroncoso/myjarvis"
echo ""
